version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: tauri_app
      POSTGRES_USER: tauri_user
      POSTGRES_PASSWORD: tauri_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro
    networks:
      - tauri_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tauri_network
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  tauri_network:
    driver: bridge