//! Application modules
//!
//! This file is auto-generated by the module management CLI.
//! Do not edit manually.

#[cfg(feature = "module-database")]
pub mod database;

#[cfg(feature = "module-auth")]
pub mod auth;

#[cfg(feature = "module-database")]
pub use database::*;
#[cfg(feature = "module-auth")]
pub use auth::*;
