name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: src-tauri

    - name: Install dependencies (Ubuntu only)
      if: matrix.platform == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

    - name: Install frontend dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build

    - name: Generate release notes
      id: release_notes
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          const tag = context.ref.replace('refs/tags/', '');
          try {
            const { data } = await github.rest.repos.generateReleaseNotes({
              owner,
              repo,
              tag_name: tag,
            });
            return data.body || 'See the commit history for changes in this release.';
          } catch (error) {
            console.warn(`Falling back to default release notes: ${error.message}`);
            return 'See the commit history for changes in this release.';
          }

    - name: Build Tauri app
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: ${{ github.ref_name }}
        releaseName: Tauri Boilerplate ${{ github.ref_name }}
        releaseBody: ${{ steps.release_notes.outputs.result }}
        releaseDraft: true
        prerelease: false
        args: --verbose

  publish-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Publish release
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          const tag = context.ref.replace('refs/tags/', '');

          // Find the draft release
          const releases = await github.rest.repos.listReleases({
            owner,
            repo,
          });

          const draftRelease = releases.data.find(release =>
            release.tag_name === tag && release.draft
          );

          if (draftRelease) {
            // Publish the release
            await github.rest.repos.updateRelease({
              owner,
              repo,
              release_id: draftRelease.id,
              draft: false,
            });

            console.log(`Published release ${tag}`);
          } else {
            console.log(`No draft release found for tag ${tag}`);
          }
